### ISSUE TITLE
fix unittests

### ISSUE THREAD

**Issue by almatn** [BME-MIT-IET/ivt-ha-2024-chuck-chuck#1]
- [x] test_remove_duplicates (TypeError)
- [x] test_summarize_ranges (AssertionError)
- [ ] test_full_path (AssertionError)
- [ ] test_simplify_path (AssertionError)
- [x] test_sort (bitonic sort)
- [x] test_stack (ordered_stack)

**Comment by CharNoir** [comment]
Working on it

**Comment by CharNoir** [comment]
**test_full_path (AssertionError)**
Is not fixable due to the fact that test created for Unix based systems and the code of full_path.py algorithm uses os library to identify full path.
And since we are using Windows based machines - we have an error during testing.
