### ISSUE TITLE
Project summary

### ISSUE THREAD

**Issue by lizzy0ne** [BME-MIT-IET/ivt-ha-2024-chuck-chuck#31]
- [ ] Summary
- [ ] Goals
- [ ] Features to work with later

**Comment by almatn** [comment]
please mention that we achieved 90% coverage, the old and new reports are in /htmlcov folder (old.html, new.html)
![image](https://github.com/BME-MIT-IET/ivt-ha-2024-chuck-chuck/assets/36095256/868f2f57-4360-43fe-9c24-922b94a19975)
